name: sherpa

channels:
  - https://conda.anaconda.org/conda-forge
  - defaults

dependencies:
  - astropy
  - bison
  - ipython
  - numpy>=1.6.0
  - numpydoc
  - matplotlib
  - sphinx
  - astropy-helpers
  - sphinx-rtd-theme
