name: Pip CI (arch)

# AstroPy does this weekly; for now I need to get this working first
#
on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
          - arch: aarch64

          # The tests on ppc64le fail rather spectacularly,
          # and it's not obvious why, so skip for now.
          #
          # - arch: ppc64le

          # We currently do not have any user requests for this
          # architecture.
          #
          # - arch: s390x

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      # As we do not include an I/O backend it is not worth checking out the data submodule.
      #
      # with:
      #   submodules: 'True'

    - name: Build and test
      uses: uraimo/run-on-arch-action@v2.1.1
      with:
        arch: ${{ matrix.arch }}
        distro: bullseye

        shell: /bin/bash

        # Based on AstroPy
        install: |
          echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
          apt-get update -q -y
          apt-get install -q -y git \
                                g++ \
                                gfortran \
                                flex \
                                bison \
                                make \
                                pkg-config \
                                python3 \
                                python3-dev \
                                python3-configobj \
                                python3-numpy \
                                python3-venv

        # Follow AstroPy for now and do not install any external packages
        # (I/O, plotting, or DS9).
        #
        run: |
          python3 -m venv --system-site-packages tests
          source tests/bin/activate

          # without this we get configure errors when building fftw and I don't know why
          #
          sed -i.orig "s|#configure=None|configure=--disable-maintainer-mode --enable-stuberrorlib --disable-shared --enable-shared=libgrp,stklib --disable-dependency-tracking|" setup.cfg

          pip3 install -e .
          pip3 install pytest
          pip3 install pytest-xdist  # not really needed here
          python3 -m pytest
